"""Add role_id to user_profiles

Revision ID: d19703c2e4fd
Revises: 
Create Date: 2025-07-15 08:23:45.086002

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd19703c2e4fd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role_id', sa.Enum('VOLUNTEER', 'ADMIN', 'PENDING_APPROVAL', name='user_roles'), nullable=False))

    with op.batch_alter_table('user_to_skill', schema=None) as batch_op:
        batch_op.add_column(sa.Column('skill_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint(batch_op.f('user_to_skill_skill_code_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'skills', ['skill_id'], ['skill_id'])
        batch_op.drop_column('skill_code')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_to_skill', schema=None) as batch_op:
        batch_op.add_column(sa.Column('skill_code', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('user_to_skill_skill_code_fkey'), 'skills', ['skill_code'], ['skill_id'])
        batch_op.drop_column('skill_id')

    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.drop_column('role_id')

    # ### end Alembic commands ###
