"""Increase length of states.name to 50

Revision ID: 4b22efeaa817
Revises: e54fcfb193b8
Create Date: 2025-07-18 12:57:26.662717

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b22efeaa817'
down_revision = 'e54fcfb193b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('states', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=13),
               type_=sa.String(length=14),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('states', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.String(length=14),
               type_=sa.VARCHAR(length=13),
               existing_nullable=False)

    # ### end Alembic commands ###
