"""your message

Revision ID: 6761f6b6813a
Revises: 4fb9b33f8fa8
Create Date: 2025-07-16 15:40:32.114165

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6761f6b6813a'
down_revision = '4fb9b33f8fa8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('skills', schema=None) as batch_op:
        batch_op.drop_column('level')

    with op.batch_alter_table('user_credentials', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)

    with op.batch_alter_table('user_to_skill', schema=None) as batch_op:
        batch_op.add_column(sa.Column('level', sa.Enum('BEGINNER', 'INTERMEDIATE', 'EXPERT', name='skilllevelenum'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_to_skill', schema=None) as batch_op:
        batch_op.drop_column('level')

    with op.batch_alter_table('user_credentials', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)

    with op.batch_alter_table('skills', schema=None) as batch_op:
        batch_op.add_column(sa.Column('level', postgresql.ENUM('BEGINNER', 'INTERMEDIATE', 'EXPERT', name='skilllevelenum'), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
