"""Added role_id to user_credentials2

Revision ID: 70f80fb756be
Revises: c877657d4988
Create Date: 2025-07-16 22:12:45.220160

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70f80fb756be'
down_revision = 'c877657d4988'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_credentials', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_confirmed_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('confirmation_token_version', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_credentials', schema=None) as batch_op:
        batch_op.drop_column('confirmation_token_version')
        batch_op.drop_column('email_confirmed_at')

    # ### end Alembic commands ###
