"""Reset migration history

Revision ID: c80074fb66b1
Revises: 
Create Date: 2025-08-04 16:19:36.664350

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c80074fb66b1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('skills', schema=None) as batch_op:
        batch_op.add_column(sa.Column('level', sa.Enum('BEGINNER', 'INTERMEDIATE', 'EXPERT', name='skilllevelenum'), nullable=False))

    with op.batch_alter_table('states', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=13),
               type_=sa.String(length=15),
               existing_nullable=False)

    with op.batch_alter_table('user_credentials', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)

    with op.batch_alter_table('user_to_skill', schema=None) as batch_op:
        batch_op.drop_column('level')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_to_skill', schema=None) as batch_op:
        batch_op.add_column(sa.Column('level', postgresql.ENUM('BEGINNER', 'INTERMEDIATE', 'EXPERT', name='skilllevelenum'), autoincrement=False, nullable=False))

    with op.batch_alter_table('user_credentials', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)

    with op.batch_alter_table('states', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.String(length=15),
               type_=sa.VARCHAR(length=13),
               existing_nullable=False)

    with op.batch_alter_table('skills', schema=None) as batch_op:
        batch_op.drop_column('level')

    # ### end Alembic commands ###
