"""Added role_id to user_credentials

Revision ID: c877657d4988
Revises: 4fb9b33f8fa8
Create Date: 2025-07-16 21:01:32.710367

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c877657d4988'
down_revision = '4fb9b33f8fa8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_credentials', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.Enum('VOLUNTEER', 'ADMIN', 'PENDING_APPROVAL', name='user_roles'), nullable=False))

    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.drop_column('role_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role_id', postgresql.ENUM('VOLUNTEER', 'ADMIN', 'PENDING_APPROVAL', name='user_roles'), autoincrement=False, nullable=False))

    with op.batch_alter_table('user_credentials', schema=None) as batch_op:
        batch_op.drop_column('role')

    # ### end Alembic commands ###
